# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hackathon2018_Client' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hackathon2018_Client

  

  platform :ios, '9.0'
  target 'Hackathon2018_ClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Hackathon2018_Client-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hackathon2018_Client-tvOS

  target 'Hackathon2018_Client-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
