# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Hackathon2018_Client_RN' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hackathon2018_Client_RN

  target 'Hackathon2018_Client_RNTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Hackathon2018_Client_RN-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hackathon2018_Client_RN-tvOS

  target 'Hackathon2018_Client_RN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
